# This file is copied into the user's config directory when they add this
# keyboard. Define any Kconfig options users may frequently want to set here,
# but leave them commented out.

# Uncomment to report battery level over BLE to the host.
# CONFIG_ZMK_BATTERY_REPORTING=y

# Uncomment to change how long the keyboard stays awake before deep sleep (ms).
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
